In [2]:
import torch
x=torch.randn(3,4,requires_grad=True)
x

tensor([[ 0.4371,  0.2457,  0.9342,  2.7290],
        [-0.9520, -0.2161,  1.2306,  0.7473],
        [ 1.1149,  0.2404, -0.5913,  0.6039]], requires_grad=True)

In [3]:
b=torch.randn(3,4,requires_grad=True)
t=x+b
y=t.sum()
y

tensor(3.5692, grad_fn=<SumBackward0>)

In [4]:
y.backward()

In [5]:
b.grad

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [6]:
x.requires_grad,b.requires_grad,t.requires_grad

(True, True, True)

In [7]:
x.is_leaf,y.is_leaf,t.is_leaf,b.is_leaf

(True, False, False, True)

In [10]:
x=torch.rand(5,3)
x

tensor([[0.6942, 0.1773, 0.4993],
        [0.4582, 0.2449, 0.7513],
        [0.8288, 0.6730, 0.8224],
        [0.2492, 0.4310, 0.4179],
        [0.7337, 0.6705, 0.3449]])

In [12]:
torch.zeros(5,3)
x.dtype

torch.float32

In [16]:
x=x.new_ones(5,3,dtype=torch.double)
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [17]:
x.shape

torch.Size([5, 3])

In [18]:
x.size()

torch.Size([5, 3])

In [21]:
y=torch.rand(5,3)
y

tensor([[0.9379, 0.5358, 0.1567],
        [0.7649, 0.2589, 0.4617],
        [0.9775, 0.7972, 0.8985],
        [0.0812, 0.7402, 0.3055],
        [0.5760, 0.7044, 0.4940]])

In [22]:
x+y

tensor([[1.9379, 1.5358, 1.1567],
        [1.7649, 1.2589, 1.4617],
        [1.9775, 1.7972, 1.8985],
        [1.0812, 1.7402, 1.3055],
        [1.5760, 1.7044, 1.4940]], dtype=torch.float64)

In [23]:
torch.add(x,y)

tensor([[1.9379, 1.5358, 1.1567],
        [1.7649, 1.2589, 1.4617],
        [1.9775, 1.7972, 1.8985],
        [1.0812, 1.7402, 1.3055],
        [1.5760, 1.7044, 1.4940]], dtype=torch.float64)

In [26]:
result=x+y
result

tensor([[1.9379, 1.5358, 1.1567],
        [1.7649, 1.2589, 1.4617],
        [1.9775, 1.7972, 1.8985],
        [1.0812, 1.7402, 1.3055],
        [1.5760, 1.7044, 1.4940]], dtype=torch.float64)

In [27]:
y

tensor([[0.9379, 0.5358, 0.1567],
        [0.7649, 0.2589, 0.4617],
        [0.9775, 0.7972, 0.8985],
        [0.0812, 0.7402, 0.3055],
        [0.5760, 0.7044, 0.4940]])

In [28]:
y.add_(x)
y

tensor([[1.9379, 1.5358, 1.1567],
        [1.7649, 1.2589, 1.4617],
        [1.9775, 1.7972, 1.8985],
        [1.0812, 1.7402, 1.3055],
        [1.5760, 1.7044, 1.4940]])

In [31]:
x[:,1:]

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]], dtype=torch.float64)

In [35]:
x=torch.randn(4,4)
x

tensor([[ 1.2891,  2.0697,  0.9655, -1.5835],
        [-0.6218, -0.1932, -1.6025, -0.6056],
        [-0.1239,  0.0209, -0.0606, -0.8414],
        [ 1.0392,  0.3557,  0.3798, -0.7009]])